file = File.open(File.expand_path("../lib/rev_manifest/version.rb", __FILE__))
version = file.read.scan(/\d+\.\d+\.\d+/).first
file.close

Gem::Specification.new do |spec|
  spec.name            = "actionview-rev_manifest"
  spec.version         = version
  spec.authors         = ["Yuku Takahashi"]
  spec.email           = ["yuku@qiita.com"]
  spec.summary         = "Let Rails load rev-manifest.json generated by gulp-rev"
  spec.homepage        = "https://github.com/yuku-t/actionview-rev_manifest"
  spec.license         = "MIT"

  spec.files           = `git ls-files -z`.split("\x0")
  spec.require_paths   = ["lib"]

  spec.add_dependency "actionview"

  spec.add_development_dependency "bundler", "~> 1.7"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rubocop", "~> 0.34.2"
end
